name: "Project Setup"
description: "Install dependencies"
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Prepare
    shell: bash
    run: |
      make prepare
  - name: 'Generate Xcode project'
    shell: bash
    run: |
      make gen
