name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/setup
        name: Setup
      - uses: ./.github/workflows/archive
        name: Archive
