name: Release

on:
  push:
    branches:
      - 'releases/**'
jobs:
  build:
    name: Release
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/setup
      - uses: ./.github/workflows/archive
